### ISSUE TITLE
image_rescale_to_voxel_size_task throws AttributeError

### ISSUE THREAD

**Issue by ecenazk** [kreshuklab/plant-seg#447]
Trying to run cell segmentation (headless mode), I seem to be stuck with constant error `AttributeError: 'list' object has no attribute 'voxels_size'` upon trying many different variotions trying the image_rescale_to_voxel_size task. The plantseg version is 2.0.0b4, I use h5 files as input where element_size_um is defined as a list [1.0, 0.108, 0.108]. I have so far tried the following versions on the config file and always had the exact same error:

1 - 
```
   - id: rescale_voxelsize
    func: image_rescale_to_voxel_size_task
    node_type: node
    images_inputs:
      image: raw
    outputs: [preproc]
    parameters:
      new_voxel_size: [1.0, 0.216, 0.216]   # treats the list as um target size (mock rescaling, sees current accessed from element_size_um = target → no resample.)
      order: 2                              # spline order
    skip: false

```
2 -
```
  - id: rescale_voxelsize
    func: image_rescale_to_voxel_size_task
    node_type: node
    images_inputs:
      image: raw
    outputs: [preproc]
    parameters:
      new_voxel_size:
        unit: um              # keep the same unit
        voxels_size:          
        - 1.0
        - 0.216
        - 0.216
      order: 2                # spline order
    skip: false
```

3 -
```
  - id: rescale_voxelsize
    func: image_rescale_to_voxel_size_task
    node_type: node
    images_inputs:
      image: raw
    outputs: [preproc]
    parameters:
      new_voxel_size:
        unit: px              # keep the same unit
        voxels_size:          
        - 1
        - 2
        - 2
      order: 2                # spline order
    skip: false
```

as the example in the complete_workflow.yaml was such:
```
- func: image_rescale_to_voxel_size_task
  id: c7e922b0-f0bc-4eaf-a59c-0e40c6a9dc5d
  images_inputs:
    image: sample_ovule_raw_set_voxel_size_smoothed_535ed9e5-3ee2-4f74-9881-856850174cc5
  node_type: node
  outputs:
  - sample_ovule_raw_set_voxel_size_smoothed_rescaled_1297c6cd-c2b7-4893-92b1-b34aaffc2c18
  parameters:
    new_voxel_size:
      unit: um
      voxels_size:
      - 0.15
      - 0.1
      - 0.1
    order: 0
  skip: false
```
I can't seem to detect where I'm going wrong. Could you maybe take a look? Thanks!
PS: ids are mock as an example, and if there are any indentation problems it is due to copy paste

More of the error if usefull:
```
  File "/data/homes/ekivan/.conda/envs/plantseg311/lib/python3.11/site-packages/plantseg/tasks/dataprocessing_tasks.py", line 218, in image_rescale_to_voxel_size_task
    spatial_scaling_factor = image.voxel_size.scalefactor_from_voxelsize(new_voxel_size)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/homes/ekivan/.conda/envs/plantseg311/lib/python3.11/site-packages/plantseg/io/voxelsize.py", line 101, in scalefactor_from_voxelsize
    if self.voxels_size is None or other.voxels_size is None:
                                   ^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'voxels_size'
```
